name: Publish to GitHub

on: 
    push:
        branches: ["main", "*"]
    pull_request:
        branches: ["main"]

jobs:
    build-macOS:
        runs-on: macos-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup xmake
              uses: xmake-io/github-action-setup-xmake@v1
              with:
                xmake-version: latest

            - name: Setup Homebrew
              run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

            - name: Setup LLVM
              run: brew install llvm

            - name: Setup Build Script
              if: ${{ runner.os != 'Windows' }}
              run: chmod +x build.sh

            - name: Build
              run: ./build.sh

            - name: Upload Artifacts
              uses: actions/upload-artifact@v4
              with:
                name: Mamba
                path: |
                    build/macosx/arm64/release/mamba

    build-windows:
        runs-on: windows-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup xmake
              uses: xmake-io/github-action-setup-xmake@v1
              with:
                xmake-version: latest

            - name: Setup Scoop
              run: |
                Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser
                Invoke-RestMethod -Uri https://get.scoop.sh | Invoke-Expression

            - name: Setup LLVM
              run: scoop install llvm

            - name: Build
              run: ./build.sh

            - name: Upload Artifacts
              uses: actions/upload-artifact@v4
              with:
                name: Mamba
                path: |
                    build/windows/x64/release/mamba.exe


